[app]
name = "Simple Survey"
category = "Apps"

[entry]
class = "SimpleSurveyApp"

[metadata]
author = "nightcaster"
license = "LGPL-3.0-only"
url = "https://github.com/nightcaster/Tildagon-SimpleSurvey.git"
description = "Create, run, and display results of surveys on your Tildagon badge."
version = 1
